import 'index.html';
import 'rsvp.html';
import '404.html'
import 'bootstrap/dist/css/bootstrap.min.css';
import 'css/main.scss';
import 'img/wasvenhoeve.jpg';
import 'img/couple.jpg';
import 'img/couple-2.jpg';
import 'img/heart.svg'
